### ISSUE TITLE
Limite não está funcionando

### ISSUE THREAD

**Issue by BADnotice** [NextPlugins/NextMarket#10]
Aparentemente o limite de itens não está funcionando, fiz o teste usando o nextmarket.vip2 e nextmarket.vip3.

   Permissões: https://prnt.sc/xgakg8, https://prnt.sc/xgao2v
   Limites: https://prnt.sc/xgatxl

**Comment by gabrielbs21** [comment]
Olá, boa tarde. Esta issue acaba de ser corrigida, você pode baixar a nova versão clicando [aqui](https://github.com/NextPlugins/NextMarket/releases/tag/v1.0.3).

Commit: [0f3efcc](https://github.com/NextPlugins/NextMarket/commit/50d7493414b6ee9d5754a371ced5d0821ff0cbac)
