### ISSUE TITLE
Economy withdraw problem

### ISSUE THREAD

**Issue by Yuhtin** [NextPlugins/NextMarket#15]
EN: 
Some savings plugins return as a successful transaction when withdrawing the player's coins even without having such amount

BR: 
Alguns plugins de economia, quando é requisitado a retirada de coins do jogador, retorna como bem sucedido mesmo sem o jogador ter os coins que está sendo retirado

**Comment by eikefab** [comment]
I've already fixed it in another commit.

Issue closed.
